version: '3'
services: 
  postgres:
    image: postgres
    restart: on-failure
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=password123
       - PGDATA=/var/lib/postgresql/data/pgdata
       - POSTGRES_DB=postgres
    volumes:
       - pgdata:/var/lib/postgresql/data
    ports:
       - 5432:5432

volumes:
  pgdata:
